version: "3.8"

services:
  hf-downloader:
    build: .
    env_file:
      - .env
    working_dir: /worker
    volumes:
      - ./data:/mnt/filestore
    ports:
      - "8080:8080"
    command: >
      gunicorn main:app
      --bind :8080
      --workers 1
      --threads 8
      --timeout 0
